# Generated by Django 5.1.7 on 2025-04-28 14:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine_Drives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(blank=True, max_length=1200)),
                ('drive_date', models.DateField()),
                ('available_slots', models.IntegerField()),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.classes')),
            ],
        ),
    ]
