# Generated by Django 5.1.7 on 2025-04-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine_drives',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
