# Generated by Django 5.1.7 on 2025-04-29 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0002_vaccine_drives_is_active'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vaccinated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('Vaccine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drives.vaccine_drives')),
            ],
        ),
    ]
