# Generated by Django 5.2 on 2025-04-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drives", "0003_students_vaccination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students_vaccination",
            name="is_vaccinated",
        ),
        migrations.AddField(
            model_name="students_vaccination",
            name="vaccination_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
